# Generated by Django 3.1.2 on 2020-11-08 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearOfEducation',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.yearofeducation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('year_of_education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.yearofeducation')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('kind', models.CharField(max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.subject')),
            ],
        ),
        migrations.CreateModel(
            name='IsTaughtBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.subject')),
            ],
        ),
        migrations.CreateModel(
            name='IsPresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLink',
            fields=[
                ('link_parameter', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.student')),
            ],
        ),
    ]
