# Generated by Django 3.1.2 on 2020-10-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
