# Generated by Django 3.1.2 on 2020-11-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0002_auto_20201108_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_token', models.CharField(max_length=700)),
                ('refresh_token', models.CharField(max_length=700)),
                ('expires_at', models.DateTimeField(verbose_name='expiration time')),
                ('client_id', models.CharField(max_length=25)),
                ('client_secret', models.CharField(max_length=32)),
            ],
        ),
    ]
