# Generated by Django 3.1.2 on 2020-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0002_auto_20201023_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLink',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_email', models.CharField(max_length=256)),
            ],
        ),
    ]
