# Generated by Django 3.1.2 on 2020-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0002_auto_20201108_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='statistics',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='student',
            name='statistics',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
    ]
