# Generated by Django 3.1.2 on 2020-11-21 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0003_zoomauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='active_token',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='expiration time'),
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='refresh_token',
            field=models.CharField(default='', max_length=700),
        ),
    ]
