# Generated by Django 3.1.2 on 2020-10-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0003_attendancelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancelink',
            old_name='id',
            new_name='link_parameter',
        ),
    ]
