# Generated by Django 3.1.2 on 2020-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0003_auto_20201114_2146'),
        ('autoAttendanceMonitoring', '0003_zoomauth'),
    ]

    operations = [
    ]
