# Generated by Django 3.1.2 on 2020-11-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0004_auto_20201023_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
