# Generated by Django 3.1.2 on 2020-11-21 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0004_merge_20201121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='statistics',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='statistics',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='active_token',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 3, 0), verbose_name='expiration time'),
        ),
        migrations.AlterField(
            model_name='zoomauth',
            name='refresh_token',
            field=models.CharField(default='', max_length=700),
        ),
    ]
