# Generated by Django 3.1.2 on 2020-11-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoAttendanceMonitoring', '0004_auto_20201121_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istaughtby',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autoAttendanceMonitoring.instructor'),
        ),
    ]
